version: "3.9"
services:
  db:
    image: postgres:16
    container_name: delivops_db
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      # IMPORTANT: double $ = pas de substitution par Compose,
      # la variable sera résolue dans le conteneur
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db_data:
